// Mock Crop Calendar Data
// Provides sample crop information when backend is unavailable

export const mockCropsData = [
    {
        _id: "1",
        name: "Wheat",
        hindiName: "गेहूं",
        season: "Rabi",
        suitableStates: ["Punjab", "Haryana", "Uttar Pradesh", "Madhya Pradesh"],
        soilTypes: ["Alluvial", "Black"],
        irrigationPercentage: 70,
        fertilizerGuidance: "NPK 120:60:40 kg/ha at basal, 40 kg N top dressing at CRI stage",
        duration: 120,
        sowingMonths: ["November", "December"],
        harvestingMonths: ["March", "April"],
        yield: "40-50 quintals/hectare",
        description: "Major Rabi crop, requires cool weather for germination and warm weather for grain development"
    },
    {
        _id: "2",
        name: "Rice",
        hindiName: "धान",
        season: "Kharif",
        suitableStates: ["Punjab", "Haryana", "West Bengal", "Andhra Pradesh", "Tamil Nadu"],
        soilTypes: ["Clayey", "Loamy"],
        irrigationPercentage: 85,
        fertilizerGuidance: "NPK 120:60:40 kg/ha, split application recommended",
        duration: 120,
        sowingMonths: ["June", "July"],
        harvestingMonths: ["October", "November"],
        yield: "50-60 quintals/hectare",
        description: "Main Kharif crop requiring plenty of water and warm climate"
    },
    {
        _id: "3",
        name: "Cotton",
        hindiName: "कपास",
        season: "Kharif",
        suitableStates: ["Gujarat", "Maharashtra", "Telangana", "Madhya Pradesh"],
        soilTypes: ["Black cotton soil", "Alluvial"],
        irrigationPercentage: 75,
        fertilizerGuidance: "NPK 100:50:50 kg/ha with micronutrients",
        duration: 180,
        sowingMonths: ["May", "June"],
        harvestingMonths: ["October", "November", "December"],
        yield: "25-30 quintals/hectare",
        description: "Important cash crop, requires moderate rainfall and long growing season"
    },
    {
        _id: "4",
        name: "Soybean",
        hindiName: "सोयाबीन",
        season: "Kharif",
        suitableStates: ["Madhya Pradesh", "Maharashtra", "Rajasthan"],
        soilTypes: ["Black", "Red", "Alluvial"],
        irrigationPercentage: 65,
        fertilizerGuidance: "NPK 30:60:40 kg/ha + Rhizobium culture",
        duration: 90,
        sowingMonths: ["June", "July"],
        harvestingMonths: ["September", "October"],
        yield: "20-25 quintals/hectare",
        description: "Important oilseed and protein crop, nitrogen fixer"
    },
    {
        _id: "5",
        name: "Chickpea",
        hindiName: "चना",
        season: "Rabi",
        suitableStates: ["Madhya Pradesh", "Maharashtra", "Rajasthan", "Uttar Pradesh"],
        soilTypes: ["Black", "Loamy"],
        irrigationPercentage: 45,
        fertilizerGuidance: "NPK 20:40:20 kg/ha + PSB culture",
        duration: 120,
        sowingMonths: ["October", "November"],
        harvestingMonths: ["February", "March"],
        yield: "15-20 quintals/hectare",
        description: "Important pulse crop, drought resistant, improves soil fertility"
    },
    {
        _id: "6",
        name: "Mustard",
        hindiName: "सरसों",
        season: "Rabi",
        suitableStates: ["Rajasthan", "Haryana", "Uttar Pradesh", "Madhya Pradesh"],
        soilTypes: ["Loamy", "Sandy loam"],
        irrigationPercentage: 50,
        fertilizerGuidance: "NPK 60:40:20 kg/ha",
        duration: 120,
        sowingMonths: ["October", "November"],
        harvestingMonths: ["February", "March"],
        yield: "12-15 quintals/hectare",
        description: "Important oilseed crop of Rabi season, requires cool climate"
    },
    {
        _id: "7",
        name: "Maize",
        hindiName: "मक्का",
        season: "Kharif",
        suitableStates: ["Karnataka", "Madhya Pradesh", "Bihar", "Uttar Pradesh"],
        soilTypes: ["Alluvial", "Red", "Black"],
        irrigationPercentage: 60,
        fertilizerGuidance: "NPK 120:60:40 kg/ha, split dose",
        duration: 90,
        sowingMonths: ["June", "July"],
        harvestingMonths: ["September", "October"],
        yield: "25-30 quintals/hectare",
        description: "Versatile cereal crop, used for food, feed and industrial purposes"
    },
    {
        _id: "8",
        name: "Sugarcane",
        hindiName: "गन्ना",
        season: "All",
        suitableStates: ["Uttar Pradesh", "Maharashtra", "Karnataka", "Tamil Nadu"],
        soilTypes: ["Loamy", "Clayey"],
        irrigationPercentage: 90,
        fertilizerGuidance: "NPK 250:115:115 kg/ha in split doses",
        duration: 365,
        sowingMonths: ["February", "March", "October", "November"],
        harvestingMonths: ["December", "January", "February"],
        yield: "700-900 quintals/hectare",
        description: "Long duration cash crop, requires abundant water and warm climate"
    },
    {
        _id: "9",
        name: "Potato",
        hindiName: "आलू",
        season: "Rabi",
        suitableStates: ["Uttar Pradesh", "West Bengal", "Bihar", "Punjab"],
        soilTypes: ["Sandy loam", "Loamy"],
        irrigationPercentage: 80,
        fertilizerGuidance: "NPK 120:60:100 kg/ha",
        duration: 90,
        sowingMonths: ["October", "November"],
        harvestingMonths: ["February", "March"],
        yield: "200-300 quintals/hectare",
        description: "Major vegetable crop, requires cool climate for tuberization"
    },
    {
        _id: "10",
        name: "Tomato",
        hindiName: "टमाटर",
        season: "Rabi",
        suitableStates: ["Andhra Pradesh", "Madhya Pradesh", "Karnataka", "Odisha"],
        soilTypes: ["Loamy", "Sandy loam", "Clayey"],
        irrigationPercentage: 70,
        fertilizerGuidance: "NPK 100:60:60 kg/ha",
        duration: 110,
        sowingMonths: ["September", "October"],
        harvestingMonths: ["December", "January"],
        yield: "250-400 quintals/hectare",
        description: "Widely grown vegetable, rich in lycopene and vitamins"
    },
    {
        _id: "11",
        name: "Onion",
        hindiName: "प्याज",
        season: "Rabi",
        suitableStates: ["Maharashtra", "Karnataka", "Madhya Pradesh", "Gujarat"],
        soilTypes: ["Loamy", "Alluvial"],
        irrigationPercentage: 75,
        fertilizerGuidance: "NPK 100:50:50 kg/ha with Sulphur",
        duration: 120,
        sowingMonths: ["October", "November"],
        harvestingMonths: ["March", "April"],
        yield: "200-250 quintals/hectare",
        description: "Essential culinary ingredient, bulb crop requiring cool weather"
    },
    {
        _id: "12",
        name: "Bajra (Pearl Millet)",
        hindiName: "बाजरा",
        season: "Kharif",
        suitableStates: ["Rajasthan", "Uttar Pradesh", "Haryana", "Gujarat"],
        soilTypes: ["Sandy", "Sandy loam"],
        irrigationPercentage: 30,
        fertilizerGuidance: "NPK 60:30:20 kg/ha",
        duration: 85,
        sowingMonths: ["June", "July"],
        harvestingMonths: ["September", "October"],
        yield: "20-25 quintals/hectare",
        description: "Drought hardy crop, staple food in arid regions"
    },
    {
        _id: "13",
        name: "Jowar (Sorghum)",
        hindiName: "ज्वार",
        season: "Kharif",
        suitableStates: ["Maharashtra", "Karnataka", "Tamil Nadu", "Madhya Pradesh"],
        soilTypes: ["Black", "Loamy"],
        irrigationPercentage: 40,
        fertilizerGuidance: "NPK 80:40:40 kg/ha",
        duration: 100,
        sowingMonths: ["June", "July"],
        harvestingMonths: ["October", "November"],
        yield: "25-30 quintals/hectare",
        description: "Versatile crop for food, feed, fodder and fuel"
    },
    {
        _id: "14",
        name: "Moong (Green Gram)",
        hindiName: "मूंग",
        season: "Zaid",
        suitableStates: ["Rajasthan", "Madhya Pradesh", "Maharashtra", "Bihar"],
        soilTypes: ["Loamy", "Sandy loam"],
        irrigationPercentage: 40,
        fertilizerGuidance: "NPK 20:40:20 kg/ha",
        duration: 65,
        sowingMonths: ["March", "April"],
        harvestingMonths: ["May", "June"],
        yield: "10-15 quintals/hectare",
        description: "Short duration pulse crop, fits well in rice-wheat rotation"
    },
    {
        _id: "15",
        name: "Groundnut",
        hindiName: "मूंगफली",
        season: "Kharif",
        suitableStates: ["Gujarat", "Andhra Pradesh", "Tamil Nadu", "Rajasthan"],
        soilTypes: ["Sandy loam", "Loamy sand"],
        irrigationPercentage: 50,
        fertilizerGuidance: "NPK 20:60:40 kg/ha + Gypsum",
        duration: 120,
        sowingMonths: ["June", "July"],
        harvestingMonths: ["October", "November"],
        yield: "15-20 quintals/hectare",
        description: "Major oilseed crop, fixes atmospheric nitrogen"
    },
    {
        _id: "16",
        name: "Cauliflower",
        hindiName: "फूलगोभी",
        season: "Rabi",
        suitableStates: ["West Bengal", "Bihar", "Uttar Pradesh", "Punjab"],
        soilTypes: ["Sandy loam", "Clay loam"],
        irrigationPercentage: 85,
        fertilizerGuidance: "NPK 120:60:60 kg/ha with Boron",
        duration: 90,
        sowingMonths: ["September", "October"],
        harvestingMonths: ["December", "January"],
        yield: "200-300 quintals/hectare",
        description: "Popular cole crop, rich in Vitamin C and K"
    },
    {
        _id: "17",
        name: "Barley",
        hindiName: "जौ",
        season: "Rabi",
        suitableStates: ["Rajasthan", "Uttar Pradesh", "Madhya Pradesh", "Punjab"],
        soilTypes: ["Sandy loam", "Loamy"],
        irrigationPercentage: 45,
        fertilizerGuidance: "NPK 60:30:20 kg/ha",
        duration: 110,
        sowingMonths: ["October", "November"],
        harvestingMonths: ["March", "April"],
        yield: "30-40 quintals/hectare",
        description: "Resilient cereal crop, used for food, malt and animal feed"
    },
    {
        _id: "18",
        name: "Urad (Black Gram)",
        hindiName: "उड़द",
        season: "Kharif",
        suitableStates: ["Madhya Pradesh", "Uttar Pradesh", "Andhra Pradesh"],
        soilTypes: ["Loamy", "Black"],
        irrigationPercentage: 40,
        fertilizerGuidance: "NPK 20:40:20 kg/ha",
        duration: 90,
        sowingMonths: ["June", "July"],
        harvestingMonths: ["September", "October"],
        yield: "8-12 quintals/hectare",
        description: "Important pulse rich in phosphoric acid"
    },
    {
        _id: "19",
        name: "Brinjal",
        hindiName: "बैंगन",
        season: "Kharif",
        suitableStates: ["West Bengal", "Odisha", "Gujarat", "Bihar"],
        soilTypes: ["Silt loam", "Clay loam"],
        irrigationPercentage: 75,
        fertilizerGuidance: "NPK 100:50:50 kg/ha",
        duration: 140,
        sowingMonths: ["June", "July"],
        harvestingMonths: ["October", "November"],
        yield: "250-300 quintals/hectare",
        description: "Popular solanaceous vegetable, wide adaptability"
    },
    {
        _id: "20",
        name: "Masoor (Lentil)",
        hindiName: "मसूर",
        season: "Rabi",
        suitableStates: ["Madhya Pradesh", "Uttar Pradesh", "Bihar", "West Bengal"],
        soilTypes: ["Loamy", "Clayey loam"],
        irrigationPercentage: 35,
        fertilizerGuidance: "NPK 20:40:20 kg/ha",
        duration: 110,
        sowingMonths: ["October", "November"],
        harvestingMonths: ["February", "March"],
        yield: "10-15 quintals/hectare",
        description: "Nutritious pulse crop, grown on residual moisture"
    },
    {
        _id: "21",
        name: "Jute",
        hindiName: "पटसन",
        season: "Kharif",
        suitableStates: ["West Bengal", "Bihar", "Assam", "Odisha"],
        soilTypes: ["Alluvial", "Clayey loam"],
        irrigationPercentage: 95,
        fertilizerGuidance: "NPK 60:30:30 kg/ha",
        duration: 120,
        sowingMonths: ["March", "April"],
        harvestingMonths: ["July", "August"],
        yield: "20-25 quintals/hectare fiber",
        description: "Golden fibre, eco-friendly biodegradable crop"
    }
];

export class MockCropCalendarService {
    static async getAllCrops() {
        // Simulate API delay
        await new Promise(resolve => setTimeout(resolve, 500));
        return mockCropsData;
    }

    static async getCropsBySeason(season) {
        // Simulate API delay
        await new Promise(resolve => setTimeout(resolve, 500));
        return mockCropsData.filter(crop => crop.season === season || crop.season === "All");
    }
}
